CREATE TABLE IF NOT EXISTS genres (
    id   INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(30) UNIQUE
);

CREATE TABLE IF NOT EXISTS rating (
    id   INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(10) UNIQUE
);

CREATE TABLE IF NOT EXISTS films (
    id           INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(30)  NOT NULL,
    description  varchar(200) NOT NULL,
    release_date DATE         NOT NULL,
    duration     INT          NOT NULL,
    rating_id    INT ,
    FOREIGN KEY (rating_id)  REFERENCES rating (id)
);

CREATE TABLE IF NOT EXISTS genre_to_film (
    film_id  INT  NOT NULL,
    genre_id INT  NOT NULL,
    FOREIGN KEY (genre_id)  REFERENCES genres (id),
    FOREIGN KEY (film_id)  REFERENCES films (id)
);

CREATE TABLE IF NOT EXISTS users (
    id        INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      varchar(30)  NOT NULL,
    email     varchar(200) NOT NULL,
    login     varchar(50)  NOT NULL,
    birthday  DATE         NOT NULL
);

CREATE TABLE IF NOT EXISTS likes (
    film_id INT  NOT NULL,
    user_id INT  NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (film_id) REFERENCES films (id)
);

CREATE TABLE IF NOT EXISTS friends (
    user_id INT  NOT NULL,
    friend_id INT  NOT NULL,
    status BOOL NOT NULL DEFAULT 'false',
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (friend_id) REFERENCES users (id)
);


